name: CD
on:
  - push
  - pull_request

jobs:
  build-win:
    name: win build (msys2)
    if: github.event_name == 'push'
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-cmake make mingw-w64-x86_64-ninja mingw-w64-x86_64-toolchain mingw-w64-x86_64-qt6-base mingw-w64-x86_64-qt6-charts mingw-w64-x86_64-qt6-svg mingw-w64-x86_64-qt6-tools mingw-w64-x86_64-nsis zip unzip

      - name: Fetch tag annotations
        run: git fetch --tags --force

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..
      - name: Build
        run: |
          cd build
          cmake --build .

      - name: Package
        id: package
        run: |
          cd build
          VERSION_NAME=`git describe`
          ../.github/scripts/package_msys.sh
          echo "VERSION_NAME=${VERSION_NAME}">> $GITHUB_OUTPUT

      - name: Upload zip to GitHub Artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: dataexplorer-win-qt6-zip
          path: ./build/package-zip/DataExplorer-win-qt6-${{ steps.package.outputs.VERSION_NAME }}.zip
          
      - name: Upload to GitHub Artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: dataexplorer-win-qt6-exe
          path: ./build/DataExplorer-win-qt6-${{ steps.package.outputs.VERSION_NAME }}.exe
        
      - name: Release exe
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
          files: |
            ./build/DataExplorer-win-qt6-${{ steps.package.outputs.VERSION_NAME }}.exe
            ./build/package-zip/DataExplorer-win-qt6-${{ steps.package.outputs.VERSION_NAME }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

###################################

  build-linux-release:
    name: linux appimage
    if: false
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetch tag annotations
      run: git fetch --tags --force

    - name: Updates
      run: sudo apt-get update

    - name: Dependencies
      run: sudo apt-get install qtbase5-dev libqt5charts5-dev qt5-default cmake 

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=appdir/usr ..

    - name: Build
      run: |
        cd build
        cmake --build .
      
    - name: Package
      id: package
      run: |
        cd build
        VERSION_NAME=`git describe`
        . ../.github/scripts/package_linux.sh
        echo "VERSION_NAME=${VERSION_NAME}">> $GITHUB_OUTPUT
        
    - name: Upload to Github Artifacts
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v3
      with:
        name: dataexplorer-linux
        path: DataExplorer-linux-${{ steps.package.outputs.VERSION_NAME }}-x86_64.AppImage
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
        files: DataExplorer-linux-${{ steps.package.outputs.VERSION_NAME }}-x86_64.AppImage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
   

   
############################
      
  macosx:
    name: Mac OS X
    runs-on: macos-latest
    if: true

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetch tag annotations
      run: git fetch --tags --force

    - name: Install Dependencies
      run: |
        wget https://github.com/sunderme/homebrew-qt6/releases/download/6.4.1/QtBase-6.4.1-Darwin.tar.xz
        sudo tar xvf ./QtBase-6.4.1-Darwin.tar.xz -C /usr/local
        rm QtBase-6.4.1-Darwin.tar.xz
        wget https://github.com/sunderme/homebrew-qt6-modules/releases/download/6.4.1/QtSvg-6.4.1-Darwin.tar.xz
        sudo tar xvf ./QtSvg-6.4.1-Darwin.tar.xz -C /usr/local/QtBase-6.4.1-Darwin --strip-components=1
        rm QtSvg-6.4.1-Darwin.tar.xz
        wget https://github.com/sunderme/homebrew-qt6-modules/releases/download/6.4.1/QtCharts-6.4.1-Darwin.tar.xz
        sudo tar xvf ./QtCharts-6.4.1-Darwin.tar.xz -C /usr/local/QtBase-6.4.1-Darwin --strip-components=1
        rm QtCharts-6.4.1-Darwin.tar.xz

    - name: Configure
      run: |
        mkdir build
        cd build
        /usr/local/QtBase-6.4.1-Darwin/bin/qt-cmake ..

    - name: Build
      run: cmake --build build

    - name: Workarounds
      run: |
        mkdir -p texstudio.app/Contents/Frameworks
        cp /usr/local/lib/libbrotlicommon.1.dylib texstudio.app/Contents/Frameworks

    - name: Package
      id: package
      run: |
        cd build
        /usr/local/QtBase-6.4.1-Darwin/bin/macdeployqt dataexplorer.app -dmg
        VERSION_NAME=`git describe`
        cp dataexplorer.dmg dataexplorer-osx-${VERSION_NAME}.dmg
        echo "VERSION_NAME=${VERSION_NAME}">> $GITHUB_OUTPUT
        
    - name: Upload to Github artifacts
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v3
      with:
        name: dataexplorer-osx
        path: build/dataexplorer-osx-${{ steps.package.outputs.VERSION_NAME }}.dmg
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
        files: build/dataexplorer-osx-${{ steps.package.outputs.VERSION_NAME }}.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        
 
